name: Package with PyInstaller

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Clean previous builds
      run: |
          cmd.exe /c "rmdir /s /q dist"
          cmd.exe /c "rmdir /s /q build"


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Package with PyInstaller
      run: |
        pyinstaller reactautomationtoolv3s.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: packaged-app
        path: dist/reactautomationtoolv3.exe
